name: smart_move_kiosk
description: Application for playing interactive games on a kiosk display.


environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  buttons_tabbar: ^1.3.0
  device_preview: ^0.7.3
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.8
  expandable: ^4.1.4
  carousel_slider: ^3.0.0
  smooth_page_indicator: ^0.2.3
  flutter_beacon: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  get: ^3.20.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/touch.svg
    - assets/images/bluetooth.png
    - assets/images/tower.png
    - assets/games.json
    - assets/game_results.json
    - assets/players.json
